Добавляет setup
htmlacademy-javascript/1402843-code-and-magick-21 pull request #3
Opened 2020-09-24 09:40 UTC by Bambukoz

2020-09-24 13:56 UTC, Shv-sergey70 requested changes

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +};
Тут происходит одно действие, которые ты выполняешь только один раз - функция не нужна.

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +};
Попробуй написать коротким синтаксисом стрелочных функций (без return). Это более предпочтительно в таком случае

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +};
Если функция содержит в названии слово `get`, это значит что она должна что-то возвращать. В данном случае функция называется `getFragment`, но она ничего не возвращает.

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +    similarList.appendChild(fragment);
Это действие нужно сделать 1 раз. То есть вне цикла. В цикле мы только заполняем фрагмент

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +getFragment(4);
4 - надо вынести в константы

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +const renderWizard = (arr) => {
Уверен что функция на вход принимает именно массив?

2020-09-24 13:56 UTC, Shv-sergey70 commented on js/setup.js
> +    fragment.appendChild(renderWizard(getRandomWizards(quantity)[i]));
`getRandomWizards` - при вызове в цикле ты создаешь много раз по 4 волшебника. Надо это сделать только 1 раз

2020-09-24 14:36 UTC, Bambukoz commented on js/setup.js
> +const renderWizard = (arr) => {
объект

2020-09-25 03:04 UTC, Shv-sergey70 approved these changes
Хорошая работа!

2020-09-25 03:04 UTC, Shv-sergey70 commented on js/setup.js
> +const createFragment = (quantity) => {
На вход стоит передавать не просто количество, а массив сгенерированных волшебников. Это удобнее, потому что не нужно помнить, сколько волшебников было создано и сколько раз надо их отрисовать. Просто итерируйся по массиву волшебников

2020-09-25 03:04 UTC, merged